apiVersion: v1
kind: ServiceAccount
metadata:
  name: MarzyIfy-serviceaccount
  namespace: MarzyIfy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: MarzyIfy-role
  namespace: MarzyIfy
rules:
  - apiGroups:
      - "*"
    resources:
      - pods
      - services
      - endpoints
      - replicasets
      - deployments
      - daemonsets
      - statefulsets
    verbs:
      - "get"
      - "list"
      - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: MarzyIfy-role-binding
  namespace: MarzyIfy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: MarzyIfy-role
subjects:
  - kind: ServiceAccount
    name: MarzyIfy-serviceaccount
    namespace: MarzyIfy
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: MarzyIfy-daemonset
  namespace: MarzyIfy
spec:
  selector:
    matchLabels:
      app: MarzyIfy
  template:
    metadata:
      labels:
        app: MarzyIfy
    spec:
      hostPID: true
      containers:
        - env:
            - name: TRACING_ENABLED
              value: "true"
            - name: METRICS_ENABLED
              value: "true"
            - name: LOGS_ENABLED
              value: "false"
            - name: BACKEND_HOST
              value: https://api-alaz.getanteon.com:443
            - name: LOG_LEVEL
              value: "1"
            - name: MONITORING_ID
              value: <MONITORING_ID>
            - name: SEND_ALIVE_TCP_CONNECTIONS
              value: "false"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          args:
            - --no-collector.wifi
            - --no-collector.hwmon
            - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/pods/.+)($|/)
            - --collector.netclass.ignored-devices=^(veth.*)$
          image: Sayawdera/MarzyIfy:v0.11.3
          imagePullPolicy: IfNotPresent
          name: MarzyIfy-pod
          ports:
            - containerPort: 8181
              protocol: TCP
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: "1"
              memory: 400Mi
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /sys/kernel/debug
              name: debugfs
              readOnly: false
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: MarzyIfy-serviceaccount
      serviceAccountName: MarzyIfy-serviceaccount
      terminationGracePeriodSeconds: 30
      volumes:
        - name: debugfs
          hostPath:
            path: /sys/kernel/debug